import { Map } from './../maps';

export enum Regions {
    Pink = 'pink',
    Brown = 'brown',
    Green = 'green',
    Red = 'red',
    Yellow = 'yellow',
}

export enum Cities {
    Hobart = 'Hobart',
    Launceston = 'Launceston',
    Geelong = 'Geelong',
    Melbourne1 = 'Melbourne 1',
    Melbourne2 = 'Melbourne 2',
    Bendigo = 'Bendigo',
    Albury = 'Albury',
    Wollongong = 'Wollongong',
    Mildura = 'Mildura',
    Dubbo = 'Dubbo',
    Canberra = 'Canberra',
    Sydney1 = 'Sydney 1',
    Syndney2 = 'Syndney 2',
    Newcastle = 'Newcastle',
    Toowoomba = 'Toowoomba',
    Goldcoast = 'Gold Coast',
    Brisbane = 'Brisbane',
    Rockhampton = 'Rockhampton',
    Mackay = 'Mackay',
    Townsville = 'Townsville',
    Cairns = 'Cairns',
    Porthedland = 'Port Hedland',
    Broome = 'Broome',
    Albany = 'Albany',
    Bunbury = 'Bunbury',
    Perth = 'Perth',
    Kalgoorlie = 'Kalgoorlie',
    Geraloton = 'Geraloton',
    Darwin = 'Darwin',
    Katherine = 'Katherine',
    Tennantcreek = 'Tennant Creek',
    Alicesprings = 'Alice Springs',
    Portaugusta = 'Port Augusta',
    Gooberpedy = 'Goober Pedy',
    Adelaide = 'Adelaide',
}

export const map: Map = {
    name: 'Australia',
    cities: [
        { name: Cities.Hobart, region: Regions.Pink, x: 1005, y: 111 },
        { name: Cities.Launceston, region: Regions.Pink, x: 1093, y: 268 },
        { name: Cities.Geelong, region: Regions.Pink, x: 1328, y: 513 },
        { name: Cities.Melbourne1, region: Regions.Pink, x: 1085, y: 495 },
        { name: Cities.Melbourne2, region: Regions.Pink, x: 1086, y: 587 },
        { name: Cities.Bendigo, region: Regions.Pink, x: 1335, y: 682 },
        { name: Cities.Albury, region: Regions.Brown, x: 1068, y: 707 },
        { name: Cities.Wollongong, region: Regions.Brown, x: 738, y: 795 },
        { name: Cities.Mildura, region: Regions.Pink, x: 1412, y: 860 },
        { name: Cities.Dubbo, region: Regions.Brown, x: 1014, y: 1092 },
        { name: Cities.Canberra, region: Regions.Brown, x: 992, y: 896 },
        { name: Cities.Sydney1, region: Regions.Brown, x: 699, y: 937 },
        { name: Cities.Syndney2, region: Regions.Brown, x: 697, y: 1028 },
        { name: Cities.Newcastle, region: Regions.Brown, x: 644, y: 1150 },
        { name: Cities.Toowoomba, region: Regions.Green, x: 832, y: 1455 },
        { name: Cities.Goldcoast, region: Regions.Green, x: 557, y: 1411 },
        { name: Cities.Brisbane, region: Regions.Green, x: 582, y: 1551 },
        { name: Cities.Rockhampton, region: Regions.Green, x: 791, y: 1778 },
        { name: Cities.Mackay, region: Regions.Green, x: 959, y: 1961 },
        { name: Cities.Townsville, region: Regions.Green, x: 1101, y: 2111 },
        { name: Cities.Cairns, region: Regions.Green, x: 1145, y: 2303 },
        { name: Cities.Porthedland, region: Regions.Red, x: 3041, y: 2002 },
        { name: Cities.Broome, region: Regions.Red, x: 2803, y: 2175 },
        { name: Cities.Albany, region: Regions.Red, x: 3136, y: 788 },
        { name: Cities.Bunbury, region: Regions.Red, x: 3366, y: 953 },
        { name: Cities.Perth, region: Regions.Red, x: 3356, y: 1096 },
        { name: Cities.Kalgoorlie, region: Regions.Red, x: 2877, y: 1195 },
        { name: Cities.Geraloton, region: Regions.Red, x: 3447, y: 1457 },
        { name: Cities.Darwin, region: Regions.Yellow, x: 2231, y: 2566 },
        { name: Cities.Katherine, region: Regions.Yellow, x: 2106, y: 2407 },
        { name: Cities.Tennantcreek, region: Regions.Yellow, x: 1990, y: 2051 },
        { name: Cities.Alicesprings, region: Regions.Yellow, x: 1971, y: 1725 },
        { name: Cities.Portaugusta, region: Regions.Yellow, x: 1703, y: 1001 },
        { name: Cities.Gooberpedy, region: Regions.Yellow, x: 1962, y: 1323 },
        { name: Cities.Adelaide, region: Regions.Yellow, x: 1668, y: 799 },
    ],
    connections: [
        { nodes: [Cities.Broome, Cities.Porthedland], cost: 13 },
        { nodes: [Cities.Kalgoorlie, Cities.Geraloton], cost: 16 },
        { nodes: [Cities.Geraloton, Cities.Perth], cost: 9 },
        { nodes: [Cities.Perth, Cities.Kalgoorlie], cost: 12 },
        { nodes: [Cities.Kalgoorlie, Cities.Albany], cost: 16 },
        { nodes: [Cities.Albany, Cities.Perth], cost: 9 },
        { nodes: [Cities.Perth, Cities.Bunbury], cost: 4 },
        { nodes: [Cities.Bunbury, Cities.Albany], cost: 6 },
        { nodes: [Cities.Cairns, Cities.Townsville], cost: 9 },
        { nodes: [Cities.Townsville, Cities.Mackay], cost: 9 },
        { nodes: [Cities.Mackay, Cities.Rockhampton], cost: 8 },
        { nodes: [Cities.Rockhampton, Cities.Toowoomba], cost: 15 },
        { nodes: [Cities.Toowoomba, Cities.Brisbane], cost: 5 },
        { nodes: [Cities.Brisbane, Cities.Rockhampton], cost: 15 },
        { nodes: [Cities.Brisbane, Cities.Goldcoast], cost: 2 },
        { nodes: [Cities.Goldcoast, Cities.Toowoomba], cost: 6 },
        { nodes: [Cities.Goldcoast, Cities.Newcastle], cost: 15 },
        { nodes: [Cities.Newcastle, Cities.Syndney2], cost: 4 },
        { nodes: [Cities.Syndney2, Cities.Sydney1], cost: 0 },
        { nodes: [Cities.Newcastle, Cities.Dubbo], cost: 10 },
        { nodes: [Cities.Dubbo, Cities.Toowoomba], cost: 18 },
        { nodes: [Cities.Sydney1, Cities.Wollongong], cost: 2 },
        { nodes: [Cities.Sydney1, Cities.Canberra], cost: 8 },
        { nodes: [Cities.Canberra, Cities.Dubbo], cost: 11 },
        { nodes: [Cities.Canberra, Cities.Newcastle], cost: 10 },
        { nodes: [Cities.Dubbo, Cities.Mildura], cost: 16 },
        { nodes: [Cities.Mildura, Cities.Canberra], cost: 16 },
        { nodes: [Cities.Canberra, Cities.Albury], cost: 7 },
        { nodes: [Cities.Mildura, Cities.Bendigo], cost: 7 },
        { nodes: [Cities.Bendigo, Cities.Melbourne2], cost: 3 },
        { nodes: [Cities.Melbourne2, Cities.Albury], cost: 9 },
        { nodes: [Cities.Mildura, Cities.Adelaide], cost: 8 },
        { nodes: [Cities.Adelaide, Cities.Portaugusta], cost: 7 },
        { nodes: [Cities.Portaugusta, Cities.Gooberpedy], cost: 11 },
        { nodes: [Cities.Mildura, Cities.Portaugusta], cost: 11 },
        { nodes: [Cities.Adelaide, Cities.Geelong], cost: 13 },
        { nodes: [Cities.Geelong, Cities.Bendigo], cost: 5 },
        { nodes: [Cities.Bendigo, Cities.Albury], cost: 6 },
        { nodes: [Cities.Wollongong, Cities.Melbourne1], cost: 19 },
        { nodes: [Cities.Melbourne1, Cities.Launceston], cost: 19 },
        { nodes: [Cities.Launceston, Cities.Hobart], cost: 5 },
        { nodes: [Cities.Melbourne1, Cities.Geelong], cost: 2 },
        { nodes: [Cities.Melbourne2, Cities.Melbourne1], cost: 0 },
        { nodes: [Cities.Gooberpedy, Cities.Alicesprings], cost: 13 },
        { nodes: [Cities.Alicesprings, Cities.Tennantcreek], cost: 10 },
        { nodes: [Cities.Tennantcreek, Cities.Katherine], cost: 14 },
        { nodes: [Cities.Katherine, Cities.Darwin], cost: 6 },
    ],
};
