// by John and Cici
import { GameMap } from './../maps';

export enum Regions {
    Pink = 'pink',
    Brown = 'brown',
    Green = 'green',
    Red = 'red',
    Yellow = 'yellow',
}

export enum Cities {
    Hobart = 'Hobart',
    Launceston = 'Launceston',
    Geelong = 'Geelong',
    Melbourne1 = 'Melbourne 1',
    Melbourne2 = 'Melbourne 2',
    Bendigo = 'Bendigo',
    Albury = 'Albury',
    Wollongong = 'Wollongong',
    Mildura = 'Mildura',
    Dubbo = 'Dubbo',
    Canberra = 'Canberra',
    Sydney1 = 'Sydney 1',
    Sydney2 = 'Sydney 2',
    Newcastle = 'Newcastle',
    Toowoomba = 'Toowoomba',
    Goldcoast = 'Gold Coast',
    Brisbane = 'Brisbane',
    Rockhampton = 'Rockhampton',
    Mackay = 'Mackay',
    Townsville = 'Townsville',
    Cairns = 'Cairns',
    Porthedland = 'Port Hedland',
    Broome = 'Broome',
    Albany = 'Albany',
    Bunbury = 'Bunbury',
    Perth = 'Perth',
    Kalgoorlie = 'Kalgoorlie',
    Geraldton = 'Geraldton',
    Darwin = 'Darwin',
    Katherine = 'Katherine',
    Tennantcreek = 'Tennant Creek',
    Alicesprings = 'Alice Springs',
    Portaugusta = 'Port Augusta',
    CooberPedy = 'Coober Pedy',
    Adelaide = 'Adelaide',
}

export const map: GameMap = {
    name: 'Australia',
    layout: 'Landscape',
    adjustRatio: [0.33, 0.33],
    mapPosition: [40, -30],
    mapRotation: 180,
    cities: [
        { name: Cities.Hobart, region: Regions.Pink, x: 540, y: 467 },
        { name: Cities.Launceston, region: Regions.Pink, x: 720, y: 500 },
        { name: Cities.Geelong, region: Regions.Pink, x: 988, y: 712 },
        { name: Cities.Melbourne1, region: Regions.Pink, x: 790, y: 650 },
        { name: Cities.Melbourne2, region: Regions.Pink, x: 790, y: 790 },
        { name: Cities.Bendigo, region: Regions.Pink, x: 1052, y: 870 },
        { name: Cities.Albury, region: Regions.Brown, x: 810, y: 983 },
        { name: Cities.Wollongong, region: Regions.Brown, x: 530, y: 1080 },
        { name: Cities.Mildura, region: Regions.Pink, x: 1185, y: 1010 },
        { name: Cities.Dubbo, region: Regions.Brown, x: 891, y: 1364 },
        { name: Cities.Canberra, region: Regions.Brown, x: 804, y: 1188 },
        { name: Cities.Sydney1, region: Regions.Brown, x: 550, y: 1230 },
        { name: Cities.Sydney2, region: Regions.Brown, x: 550, y: 1380 },
        { name: Cities.Newcastle, region: Regions.Brown, x: 530, y: 1545 },
        { name: Cities.Toowoomba, region: Regions.Green, x: 1010, y: 1660 },
        { name: Cities.Goldcoast, region: Regions.Green, x: 660, y: 1730 },
        { name: Cities.Brisbane, region: Regions.Green, x: 740, y: 1885 },
        { name: Cities.Rockhampton, region: Regions.Green, x: 1040, y: 1987 },
        { name: Cities.Mackay, region: Regions.Green, x: 1260, y: 2101 },
        { name: Cities.Townsville, region: Regions.Green, x: 1445, y: 2193 },
        { name: Cities.Cairns, region: Regions.Green, x: 1652, y: 2209 },
        { name: Cities.Porthedland, region: Regions.Red, x: 2741, y: 2002 },
        { name: Cities.Broome, region: Regions.Red, x: 2503, y: 2175 },
        { name: Cities.Albany, region: Regions.Red, x: 2400, y: 850 },
        { name: Cities.Bunbury, region: Regions.Red, x: 2700, y: 1030 },
        { name: Cities.Perth, region: Regions.Red, x: 2680, y: 1230 },
        { name: Cities.Kalgoorlie, region: Regions.Red, x: 2177, y: 1295 },
        { name: Cities.Geraldton, region: Regions.Red, x: 2747, y: 1557 },
        { name: Cities.Darwin, region: Regions.Yellow, x: 2264, y: 2016 },
        { name: Cities.Katherine, region: Regions.Yellow, x: 2105, y: 1947 },
        { name: Cities.Tennantcreek, region: Regions.Yellow, x: 1905, y: 1736 },
        { name: Cities.Alicesprings, region: Regions.Yellow, x: 1803, y: 1512 },
        { name: Cities.Portaugusta, region: Regions.Yellow, x: 1520, y: 1094 },
        { name: Cities.CooberPedy, region: Regions.Yellow, x: 1850, y: 1232 },
        { name: Cities.Adelaide, region: Regions.Yellow, x: 1430, y: 863 },
    ],
    connections: [
        { nodes: [Cities.Broome, Cities.Porthedland], cost: 13 },
        { nodes: [Cities.Kalgoorlie, Cities.Geraldton], cost: 16 },
        { nodes: [Cities.Geraldton, Cities.Perth], cost: 9 },
        { nodes: [Cities.Perth, Cities.Kalgoorlie], cost: 12 },
        { nodes: [Cities.Kalgoorlie, Cities.Albany], cost: 16 },
        { nodes: [Cities.Albany, Cities.Perth], cost: 9 },
        { nodes: [Cities.Perth, Cities.Bunbury], cost: 4 },
        { nodes: [Cities.Bunbury, Cities.Albany], cost: 6 },
        { nodes: [Cities.Cairns, Cities.Townsville], cost: 9 },
        { nodes: [Cities.Townsville, Cities.Mackay], cost: 9 },
        { nodes: [Cities.Mackay, Cities.Rockhampton], cost: 8 },
        { nodes: [Cities.Rockhampton, Cities.Toowoomba], cost: 15 },
        { nodes: [Cities.Toowoomba, Cities.Brisbane], cost: 5 },
        { nodes: [Cities.Brisbane, Cities.Rockhampton], cost: 15 },
        { nodes: [Cities.Brisbane, Cities.Goldcoast], cost: 2 },
        { nodes: [Cities.Goldcoast, Cities.Toowoomba], cost: 6 },
        { nodes: [Cities.Goldcoast, Cities.Newcastle], cost: 15 },
        { nodes: [Cities.Newcastle, Cities.Sydney2], cost: 4 },
        { nodes: [Cities.Sydney2, Cities.Sydney1], cost: 0 },
        { nodes: [Cities.Newcastle, Cities.Dubbo], cost: 10 },
        { nodes: [Cities.Dubbo, Cities.Toowoomba], cost: 18 },
        { nodes: [Cities.Sydney1, Cities.Wollongong], cost: 2 },
        { nodes: [Cities.Sydney1, Cities.Canberra], cost: 8 },
        { nodes: [Cities.Canberra, Cities.Dubbo], cost: 11 },
        { nodes: [Cities.Canberra, Cities.Newcastle], cost: 10 },
        { nodes: [Cities.Dubbo, Cities.Mildura], cost: 16 },
        { nodes: [Cities.Mildura, Cities.Canberra], cost: 16 },
        { nodes: [Cities.Canberra, Cities.Albury], cost: 7 },
        { nodes: [Cities.Mildura, Cities.Bendigo], cost: 7 },
        { nodes: [Cities.Bendigo, Cities.Melbourne2], cost: 3 },
        { nodes: [Cities.Melbourne2, Cities.Albury], cost: 9 },
        { nodes: [Cities.Mildura, Cities.Adelaide], cost: 8 },
        { nodes: [Cities.Adelaide, Cities.Portaugusta], cost: 7 },
        { nodes: [Cities.Portaugusta, Cities.CooberPedy], cost: 11 },
        { nodes: [Cities.Mildura, Cities.Portaugusta], cost: 11 },
        { nodes: [Cities.Adelaide, Cities.Geelong], cost: 13 },
        { nodes: [Cities.Geelong, Cities.Bendigo], cost: 5 },
        { nodes: [Cities.Bendigo, Cities.Albury], cost: 6 },
        { nodes: [Cities.Wollongong, Cities.Melbourne1], cost: 19 },
        { nodes: [Cities.Melbourne1, Cities.Launceston], cost: 19 },
        { nodes: [Cities.Launceston, Cities.Hobart], cost: 5 },
        { nodes: [Cities.Melbourne1, Cities.Geelong], cost: 2 },
        { nodes: [Cities.Melbourne2, Cities.Melbourne1], cost: 0 },
        { nodes: [Cities.CooberPedy, Cities.Alicesprings], cost: 13 },
        { nodes: [Cities.Alicesprings, Cities.Tennantcreek], cost: 10 },
        { nodes: [Cities.Tennantcreek, Cities.Katherine], cost: 14 },
        { nodes: [Cities.Katherine, Cities.Darwin], cost: 6 },
    ],
};
