import { GameMap } from './../maps';

export enum Regions {
    Brown = 'brown',
    Green = 'green',
    Purple = 'purple',
    Yellow = 'yellow',
    Red = 'red',
}

export enum Cities {
    Asahikawa = 'Asahikawa',
    Sapporo = 'Sapporo',
    Hakodate = 'Hakodate',
    Admori = 'Admori',
    Morioka = 'Morioka',
    Akita = 'Akita',
    Sendai = 'Sendai',
    Niigata = 'Niigata',
    Koriyama = 'Koriyama',
    Nagano = 'Nagano',
    Saitama = 'Saitama',
    Tokyo = 'Tokyo',
    Chiba = 'Chiba',
    Yokohama = 'Yokohama',
    Kanazawa = 'Kanazawa',
    Toyama = 'Toyama',
    Kyoto = 'Kyoto',
    Osaka = 'Osaka',
    Nagoya = 'Nagoya',
    Kofu = 'Kofu',
    Hamamatsu = 'Hamamatsu',
    Kobe = 'Kobe',
    Matsue = 'Matsue',
    Okayama = 'Okayama',
    Takamatsu = 'Takamatsu',
    Kochi = 'Kochi',
    Matsuyama = 'Matsuyama',
    Hiroshima = 'Hiroshima',
    Shimonoseki = 'Shimonoseki',
    Oita = 'Oita',
    Miyazaki = 'Miyazaki',
    Kagoshima = 'Kagoshima',
    Kumamoto = 'Kumamoto',
    Fukuoka = 'Fukuoka',
    Nagasaki = 'Nagasaki',
}

export const map: GameMap = {
    name: 'Japan',
    cities: [
        { name: Cities.Asahikawa, region: Regions.Brown, x: 3384, y: 1014 },
        { name: Cities.Sapporo, region: Regions.Brown, x: 3028, y: 982, slotCosts: [10, 10, 20], stepSlots: [2, 2, 3] },
        { name: Cities.Hakodate, region: Regions.Brown, x: 2622, y: 1112 },
        { name: Cities.Admori, region: Regions.Brown, x: 3818, y: 1336 },
        { name: Cities.Morioka, region: Regions.Brown, x: 3636, y: 1646, slotCosts: [15, 20], stepSlots: [0, 1, 2] },
        { name: Cities.Akita, region: Regions.Brown, x: 3472, y: 1480 },
        { name: Cities.Sendai, region: Regions.Brown, x: 3408, y: 1886 },
        { name: Cities.Niigata, region: Regions.Green, x: 2874, y: 1628 },
        { name: Cities.Koriyama, region: Regions.Green, x: 3086, y: 1932, slotCosts: [10, 15] },
        { name: Cities.Nagano, region: Regions.Green, x: 2486, y: 1722 },
        { name: Cities.Saitama, region: Regions.Green, x: 2450, y: 1986, slotCosts: [15, 20], stepSlots: [0, 1, 2] },
        { name: Cities.Tokyo, region: Regions.Green, x: 2524, y: 2122, slotCosts: [10, 10, 20], stepSlots: [2, 2, 3] },
        { name: Cities.Chiba, region: Regions.Green, x: 2650, y: 2316 },
        {
            name: Cities.Yokohama,
            region: Regions.Green,
            x: 2306,
            y: 2244,
            slotCosts: [10, 10, 20],
            stepSlots: [2, 2, 3],
        },
        { name: Cities.Kanazawa, region: Regions.Purple, x: 2207, y: 1385 },
        { name: Cities.Toyama, region: Regions.Purple, x: 2257, y: 1595, slotCosts: [15, 20], stepSlots: [0, 1, 2] },
        { name: Cities.Kyoto, region: Regions.Purple, x: 1765, y: 1595 },
        { name: Cities.Osaka, region: Regions.Purple, x: 1517, y: 1631, slotCosts: [10, 10, 20], stepSlots: [2, 2, 3] },
        { name: Cities.Nagoya, region: Regions.Purple, x: 1942, y: 1751 },
        { name: Cities.Kofu, region: Regions.Purple, x: 2179, y: 1897 },
        { name: Cities.Hamamatsu, region: Regions.Purple, x: 1958, y: 2024, slotCosts: [10, 15] },
        { name: Cities.Kobe, region: Regions.Yellow, x: 1555, y: 1451, slotCosts: [10, 10, 20], stepSlots: [2, 2, 3] },
        { name: Cities.Matsue, region: Regions.Yellow, x: 1457, y: 1006, slotCosts: [15, 20], stepSlots: [0, 1, 2] },
        { name: Cities.Okayama, region: Regions.Yellow, x: 1390, y: 1286 },
        { name: Cities.Takamatsu, region: Regions.Yellow, x: 1268, y: 1507 },
        { name: Cities.Kochi, region: Regions.Yellow, x: 974, y: 1472, slotCosts: [10, 15] },
        { name: Cities.Matsuyama, region: Regions.Yellow, x: 1036, y: 1268 },
        { name: Cities.Hiroshima, region: Regions.Yellow, x: 1103, y: 1078 },
        { name: Cities.Shimonoseki, region: Regions.Red, x: 856, y: 962 },
        { name: Cities.Oita, region: Regions.Red, x: 731, y: 1166, slotCosts: [10, 15] },
        { name: Cities.Miyazaki, region: Regions.Red, x: 469, y: 1318, slotCosts: [15, 20], stepSlots: [0, 1, 2] },
        { name: Cities.Kagoshima, region: Regions.Red, x: 157, y: 1255 },
        { name: Cities.Kumamoto, region: Regions.Red, x: 457, y: 1045 },
        { name: Cities.Fukuoka, region: Regions.Red, x: 644, y: 823, slotCosts: [10, 10, 20], stepSlots: [2, 2, 3] },
        { name: Cities.Nagasaki, region: Regions.Red, x: 313, y: 875 },
    ],
    layout: 'Portrait',
    adjustRatio: [0.28, 0.28],
    mapPosition: [0, 120],
    resupply: [
        // Coal
        [
            [3, 4, 3], // 2P
            [4, 5, 3], // 3P
            [5, 6, 4], // 4P
            [5, 7, 5], // 5P
            [7, 9, 6], // 6P
        ],
        // Oil
        [
            [2, 2, 4],
            [2, 3, 4],
            [3, 4, 5],
            [4, 5, 6],
            [5, 6, 7],
        ],
        // Garbage
        [
            [1, 2, 3],
            [1, 2, 3],
            [2, 3, 4],
            [3, 3, 5],
            [3, 5, 6],
        ],
        // Uranium
        [
            [1, 1, 1],
            [1, 1, 1],
            [1, 2, 2],
            [2, 3, 2],
            [2, 3, 3],
        ],
    ],
    startingResources: [21, 15, 9, 3],
    startingCities: ['Fukuoka', 'Kobe', 'Osaka', 'Sapporo', 'Tokyo', 'Yokohama'],
    mapSpecificRules:
        'Users may build 0, 1, 2 houses in round 1. The first house you place MUST be in one of the six special starting cities: Fukuoka, Kobe, Osaka, Sapporo, Tokyo, or Yokohama whether it be round 1 or after.\n' +
        'You get a free jump but that free jump can only go into one of these six starting cities (you still pay for the house, just no connection fee).\n' +
        'All of these six special starting cities are [10, 10, 20] meaning two players can go there in step 1 and these cities are marked with 10 on the map.\n' +
        'If you build 2 cities in round 1, you must use your free jump even though they might have 0 connection like Tokyo and Yokohama (system will auto use your free jump).\n' +
        'In Step 3, the third connection spots (cost 20) are opened in the starting cities and are available for normal or free jump.\n' +
        'Some smaller cities have only two building spots (10 and 15, or 15 and 20). These cities are marked with an X. An X at the top means no Step 1 builds, an X at the bottom means no Step 3 builds.\n' +
        'If all starting city spots are taken, you cannot use your free jump.',
    connections: [
        { nodes: [Cities.Nagasaki, Cities.Fukuoka], cost: 10 },
        { nodes: [Cities.Fukuoka, Cities.Shimonoseki], cost: 10 },
        { nodes: [Cities.Shimonoseki, Cities.Hiroshima], cost: 12 },
        { nodes: [Cities.Hiroshima, Cities.Matsue], cost: 13 },
        { nodes: [Cities.Kumamoto, Cities.Kagoshima], cost: 13 },
        { nodes: [Cities.Kagoshima, Cities.Miyazaki], cost: 8 },
        { nodes: [Cities.Miyazaki, Cities.Kumamoto], cost: 11 },
        { nodes: [Cities.Kumamoto, Cities.Oita], cost: 12 },
        { nodes: [Cities.Oita, Cities.Miyazaki], cost: 12 },
        { nodes: [Cities.Oita, Cities.Matsuyama], cost: 14 },
        { nodes: [Cities.Matsuyama, Cities.Kochi], cost: 7 },
        { nodes: [Cities.Kochi, Cities.Takamatsu], cost: 9 },
        { nodes: [Cities.Hiroshima, Cities.Okayama], cost: 11 },
        { nodes: [Cities.Okayama, Cities.Matsue], cost: 11 },
        { nodes: [Cities.Okayama, Cities.Kobe], cost: 9 },
        { nodes: [Cities.Kobe, Cities.Matsue], cost: 16 },
        { nodes: [Cities.Matsuyama, Cities.Takamatsu], cost: 10 },
        { nodes: [Cities.Takamatsu, Cities.Okayama], cost: 9 },
        { nodes: [Cities.Osaka, Cities.Nagoya], cost: 9 },
        { nodes: [Cities.Nagoya, Cities.Kyoto], cost: 9 },
        { nodes: [Cities.Kyoto, Cities.Kobe], cost: 3 },
        { nodes: [Cities.Osaka, Cities.Kyoto], cost: 0 },
        { nodes: [Cities.Kyoto, Cities.Kanazawa], cost: 19 },
        { nodes: [Cities.Kanazawa, Cities.Toyama], cost: 3 },
        { nodes: [Cities.Kanazawa, Cities.Nagoya], cost: 16 },
        { nodes: [Cities.Nagoya, Cities.Toyama], cost: 15 },
        { nodes: [Cities.Toyama, Cities.Nagano], cost: 9 },
        { nodes: [Cities.Nagano, Cities.Niigata], cost: 12 },
        { nodes: [Cities.Niigata, Cities.Akita], cost: 16 },
        { nodes: [Cities.Hamamatsu, Cities.Kofu], cost: 12 },
        { nodes: [Cities.Kofu, Cities.Nagoya], cost: 15 },
        { nodes: [Cities.Nagoya, Cities.Hamamatsu], cost: 6 },
        { nodes: [Cities.Kofu, Cities.Saitama], cost: 8 },
        { nodes: [Cities.Saitama, Cities.Tokyo], cost: 0 },
        { nodes: [Cities.Tokyo, Cities.Yokohama], cost: 0 },
        { nodes: [Cities.Tokyo, Cities.Chiba], cost: 4 },
        { nodes: [Cities.Chiba, Cities.Sendai], cost: 21 },
        { nodes: [Cities.Tokyo, Cities.Koriyama], cost: 14 },
        { nodes: [Cities.Koriyama, Cities.Niigata], cost: 11 },
        { nodes: [Cities.Saitama, Cities.Nagano], cost: 17 },
        { nodes: [Cities.Saitama, Cities.Niigata], cost: 21 },
        { nodes: [Cities.Koriyama, Cities.Sendai], cost: 7 },
        { nodes: [Cities.Sendai, Cities.Akita], cost: 14 },
        { nodes: [Cities.Akita, Cities.Koriyama], cost: 21 },
        { nodes: [Cities.Sendai, Cities.Morioka], cost: 10 },
        { nodes: [Cities.Morioka, Cities.Akita], cost: 7 },
        { nodes: [Cities.Akita, Cities.Admori], cost: 10 },
        { nodes: [Cities.Admori, Cities.Morioka], cost: 10 },
        { nodes: [Cities.Admori, Cities.Hakodate], cost: 15 },
        { nodes: [Cities.Hakodate, Cities.Sapporo], cost: 14 },
        { nodes: [Cities.Sapporo, Cities.Asahikawa], cost: 8 },
        { nodes: [Cities.Kumamoto, Cities.Shimonoseki], cost: 16 },
        { nodes: [Cities.Kumamoto, Cities.Fukuoka], cost: 8 },
    ],
};

export const mapRecharged: GameMap = { ...map };
