import { GameMap } from './../maps';

export enum Regions {
    Pink = 'pink',
    Green = 'green',
    Orange = 'orange',
    Yellow = 'yellow',
    Red = 'red',
    Brown = 'brown',
}

export enum Cities {
    Mashhad = 'Mashhad',
    Corgan = 'Corgan',
    Tehran = 'Tehran',
    Tabriz = 'Tabriz',
    Mosul = 'Mosul',
    Kermanshah = 'Kermanshah',
    Baghdad = 'Baghdad',
    Isfahan = 'Isfahan',
    Yazo = 'Yazo',
    Zahedan = 'Zahedan',
    Kerman = 'Kerman',
    Shiraz = 'Shiraz',
    Bandarabbas = 'Bandar Abbas',
    Chabahar = 'Chabahar',
    Dubai = 'Dubai',
    Muscat = 'Muscat',
    Abudhari = 'Abu Dhari',
    Alain = 'Alain',
    Salalah = 'Salalah',
    Doha = 'Doha',
    Manama = 'Manama',
    Ahvaz = 'Ahvaz',
    Basra = 'Basra',
    Najaf = 'Najaf',
    Kuwaitcity = 'Kuwait City',
    Buraydah = 'Buraydah',
    Riyadh = 'Riyadh',
    Medina = 'Medina',
    Alhasahah = 'Al Hasahah',
    Aleppo = 'Aleppo',
    Damascus = 'Damascus',
    Amman = 'Amman',
    Beirut = 'Beirut',
    Jerusalem = 'Jerusalem',
    Aqaba = 'Aqaba',
    Mukalla = 'Mukalla',
    Sanaa = 'Sanaa',
    Aden = 'Aden',
    Alhudaydah = 'Al-Hudaydah',
    Abha = 'Abha',
    Mecca = 'Mecca',
    Jeddah = 'Jeddah',
}

export const map: GameMap = {
    name: 'Middle East',
    cities: [
        { name: Cities.Mashhad, region: Regions.Pink, x: 859, y: 327 },
        { name: Cities.Corgan, region: Regions.Pink, x: 734, y: 287 },
        { name: Cities.Tehran, region: Regions.Pink, x: 633, y: 342 },
        { name: Cities.Tabriz, region: Regions.Pink, x: 450, y: 251 },
        { name: Cities.Mosul, region: Regions.Pink, x: 352, y: 307 },
        { name: Cities.Kermanshah, region: Regions.Pink, x: 503, y: 391 },
        { name: Cities.Baghdad, region: Regions.Pink, x: 393, y: 406 },
        { name: Cities.Isfahan, region: Regions.Green, x: 621, y: 436 },
        { name: Cities.Yazo, region: Regions.Green, x: 720, y: 472 },
        { name: Cities.Zahedan, region: Regions.Green, x: 896, y: 547 },
        { name: Cities.Kerman, region: Regions.Green, x: 784, y: 534 },
        { name: Cities.Shiraz, region: Regions.Green, x: 651, y: 557 },
        { name: Cities.Bandarabbas, region: Regions.Green, x: 756, y: 629 },
        { name: Cities.Chabahar, region: Regions.Green, x: 898, y: 687 },
        { name: Cities.Dubai, region: Regions.Orange, x: 752, y: 690 },
        { name: Cities.Muscat, region: Regions.Orange, x: 828, y: 773 },
        { name: Cities.Abudhari, region: Regions.Orange, x: 692, y: 747 },
        { name: Cities.Alain, region: Regions.Orange, x: 715, y: 812 },
        { name: Cities.Salalah, region: Regions.Orange, x: 694, y: 981 },
        { name: Cities.Doha, region: Regions.Orange, x: 596, y: 713 },
        { name: Cities.Manama, region: Regions.Orange, x: 532, y: 652 },
        { name: Cities.Ahvaz, region: Regions.Yellow, x: 555, y: 499 },
        { name: Cities.Basra, region: Regions.Yellow, x: 452, y: 519 },
        { name: Cities.Najaf, region: Regions.Yellow, x: 356, y: 478 },
        { name: Cities.Kuwaitcity, region: Regions.Yellow, x: 500, y: 580 },
        { name: Cities.Buraydah, region: Regions.Yellow, x: 360, y: 674 },
        { name: Cities.Riyadh, region: Regions.Yellow, x: 443, y: 741 },
        { name: Cities.Medina, region: Regions.Yellow, x: 264, y: 738 },
        { name: Cities.Alhasahah, region: Regions.Red, x: 248, y: 300 },
        { name: Cities.Aleppo, region: Regions.Red, x: 132, y: 315 },
        { name: Cities.Damascus, region: Regions.Red, x: 186, y: 433 },
        { name: Cities.Amman, region: Regions.Red, x: 171, y: 493 },
        { name: Cities.Beirut, region: Regions.Red, x: 94, y: 401 },
        { name: Cities.Jerusalem, region: Regions.Red, x: 76, y: 481 },
        { name: Cities.Aqaba, region: Regions.Red, x: 103, y: 563 },
        { name: Cities.Mukalla, region: Regions.Brown, x: 555, y: 1059 },
        { name: Cities.Sanaa, region: Regions.Brown, x: 426, y: 1018 },
        { name: Cities.Aden, region: Regions.Brown, x: 431, y: 1105 },
        { name: Cities.Alhudaydah, region: Regions.Brown, x: 317, y: 1057 },
        { name: Cities.Abha, region: Regions.Brown, x: 306, y: 938 },
        { name: Cities.Mecca, region: Regions.Brown, x: 280, y: 850 },
        { name: Cities.Jeddah, region: Regions.Brown, x: 190, y: 800 },
    ],
    connections: [
        { nodes: [Cities.Tabriz, Cities.Tehran], cost: 13 },
        { nodes: [Cities.Tehran, Cities.Corgan], cost: 9 },
        { nodes: [Cities.Corgan, Cities.Mashhad], cost: 12 },
        { nodes: [Cities.Mashhad, Cities.Zahedan], cost: 20 },
        { nodes: [Cities.Zahedan, Cities.Kerman], cost: 10 },
        { nodes: [Cities.Kerman, Cities.Yazo], cost: 7 },
        { nodes: [Cities.Yazo, Cities.Mashhad], cost: 18 },
        { nodes: [Cities.Mashhad, Cities.Tehran], cost: 19 },
        { nodes: [Cities.Tehran, Cities.Yazo], cost: 12 },
        { nodes: [Cities.Yazo, Cities.Shiraz], cost: 9 },
        { nodes: [Cities.Shiraz, Cities.Kerman], cost: 11 },
        { nodes: [Cities.Yazo, Cities.Isfahan], cost: 7 },
        { nodes: [Cities.Isfahan, Cities.Shiraz], cost: 10 },
        { nodes: [Cities.Isfahan, Cities.Tehran], cost: 9 },
        { nodes: [Cities.Tehran, Cities.Kermanshah], cost: 13 },
        { nodes: [Cities.Kermanshah, Cities.Isfahan], cost: 13 },
        { nodes: [Cities.Isfahan, Cities.Ahvaz], cost: 11 },
        { nodes: [Cities.Ahvaz, Cities.Shiraz], cost: 11 },
        { nodes: [Cities.Ahvaz, Cities.Kermanshah], cost: 11 },
        { nodes: [Cities.Kermanshah, Cities.Tabriz], cost: 13 },
        { nodes: [Cities.Tabriz, Cities.Mosul], cost: 13 },
        { nodes: [Cities.Mosul, Cities.Baghdad], cost: 8 },
        { nodes: [Cities.Baghdad, Cities.Kermanshah], cost: 8 },
        { nodes: [Cities.Basra, Cities.Ahvaz], cost: 3 },
        { nodes: [Cities.Ahvaz, Cities.Kuwaitcity], cost: 7 },
        { nodes: [Cities.Kuwaitcity, Cities.Basra], cost: 5 },
        { nodes: [Cities.Basra, Cities.Najaf], cost: 10 },
        { nodes: [Cities.Najaf, Cities.Baghdad], cost: 4 },
        { nodes: [Cities.Baghdad, Cities.Basra], cost: 12 },
        { nodes: [Cities.Alhasahah, Cities.Mosul], cost: 4 },
        { nodes: [Cities.Alhasahah, Cities.Baghdad], cost: 11 },
        { nodes: [Cities.Baghdad, Cities.Damascus], cost: 16 },
        { nodes: [Cities.Damascus, Cities.Najaf], cost: 15 },
        { nodes: [Cities.Alhasahah, Cities.Damascus], cost: 14 },
        { nodes: [Cities.Damascus, Cities.Amman], cost: 4 },
        { nodes: [Cities.Amman, Cities.Aqaba], cost: 7 },
        { nodes: [Cities.Aqaba, Cities.Jerusalem], cost: 6 },
        { nodes: [Cities.Jerusalem, Cities.Amman], cost: 3 },
        { nodes: [Cities.Jerusalem, Cities.Beirut], cost: 6 },
        { nodes: [Cities.Beirut, Cities.Damascus], cost: 4 },
        { nodes: [Cities.Damascus, Cities.Aleppo], cost: 8 },
        { nodes: [Cities.Aleppo, Cities.Beirut], cost: 9 },
        { nodes: [Cities.Aleppo, Cities.Alhasahah], cost: 7 },
        { nodes: [Cities.Baghdad, Cities.Tabriz], cost: 18 },
        { nodes: [Cities.Zahedan, Cities.Chabahar], cost: 13 },
        { nodes: [Cities.Zahedan, Cities.Bandarabbas], cost: 14 },
        { nodes: [Cities.Bandarabbas, Cities.Kerman], cost: 13 },
        { nodes: [Cities.Shiraz, Cities.Bandarabbas], cost: 14 },
        { nodes: [Cities.Bandarabbas, Cities.Chabahar], cost: 15 },
        { nodes: [Cities.Kuwaitcity, Cities.Manama], cost: 12 },
        { nodes: [Cities.Manama, Cities.Doha], cost: 6 },
        { nodes: [Cities.Doha, Cities.Abudhari], cost: 9 },
        { nodes: [Cities.Abudhari, Cities.Dubai], cost: 2 },
        { nodes: [Cities.Dubai, Cities.Muscat], cost: 9 },
        { nodes: [Cities.Muscat, Cities.Alain], cost: 7 },
        { nodes: [Cities.Alain, Cities.Abudhari], cost: 3 },
        { nodes: [Cities.Alain, Cities.Dubai], cost: 3 },
        { nodes: [Cities.Riyadh, Cities.Alain], cost: 23 },
        { nodes: [Cities.Doha, Cities.Riyadh], cost: 12 },
        { nodes: [Cities.Riyadh, Cities.Manama], cost: 10 },
        { nodes: [Cities.Riyadh, Cities.Kuwaitcity], cost: 12 },
        { nodes: [Cities.Kuwaitcity, Cities.Buraydah], cost: 12 },
        { nodes: [Cities.Buraydah, Cities.Riyadh], cost: 7 },
        { nodes: [Cities.Buraydah, Cities.Medina], cost: 10 },
        { nodes: [Cities.Medina, Cities.Riyadh], cost: 15 },
        { nodes: [Cities.Buraydah, Cities.Najaf], cost: 14 },
        { nodes: [Cities.Aqaba, Cities.Jeddah], cost: 23 },
        { nodes: [Cities.Aqaba, Cities.Medina], cost: 17 },
        { nodes: [Cities.Medina, Cities.Jeddah], cost: 7 },
        { nodes: [Cities.Jeddah, Cities.Mecca], cost: 1 },
        { nodes: [Cities.Mecca, Cities.Medina], cost: 7 },
        { nodes: [Cities.Mecca, Cities.Riyadh], cost: 17 },
        { nodes: [Cities.Riyadh, Cities.Abha], cost: 19 },
        { nodes: [Cities.Abha, Cities.Mecca], cost: 12 },
        { nodes: [Cities.Salalah, Cities.Muscat], cost: 21 },
        { nodes: [Cities.Alain, Cities.Salalah], cost: 18 },
        { nodes: [Cities.Salalah, Cities.Mukalla], cost: 15 },
        { nodes: [Cities.Salalah, Cities.Sanaa], cost: 25 },
        { nodes: [Cities.Sanaa, Cities.Mukalla], cost: 14 },
        { nodes: [Cities.Mukalla, Cities.Aden], cost: 13 },
        { nodes: [Cities.Aden, Cities.Alhudaydah], cost: 9 },
        { nodes: [Cities.Alhudaydah, Cities.Abha], cost: 10 },
        { nodes: [Cities.Abha, Cities.Sanaa], cost: 11 },
        { nodes: [Cities.Sanaa, Cities.Alhudaydah], cost: 5 },
    ],
    layout: 'Portrait',
    mapPosition: [0, -100],
    resupply: [
        [
            [2, 1, 1],
            [2, 1, 1],
            [3, 2, 2],
            [4, 3, 2],
            [5, 4, 3],
        ],
        [
            [5, 3, 2],
            [5, 3, 2],
            [6, 3, 2],
            [8, 4, 3],
            [9, 5, 4],
        ],
        [
            [1, 3, 4],
            [1, 3, 4],
            [1, 4, 6],
            [1, 4, 8],
            [1, 6, 9],
        ],
        [
            [0, 2, 2],
            [0, 2, 2],
            [0, 3, 3],
            [0, 3, 4],
            [0, 4, 5],
        ],
    ],
    startingResources: [21, 21, 3, 3],
    startingSupply: [24, 24, 21, 11],
    mapSpecificRules:
        'Only coal and oil can be bought for $1, and any number of oil can restock at $1. During step 1, garbage and nuclear plants will be removed from the current market. Step 2 will be triggered after going through the deck once rather than by a specific number of cities. Step 3 will be triggered after going through the deck a second time.',
};
