import { Map } from './../maps';

export enum Regions {
    Brown = 'brown',
    Yellow = 'yellow',
    Pink = 'pink',
    Purple = 'purple',
    Orange = 'orange',
    Red = 'red',
}

export enum Cities {
    Oulu = 'Oulu',
    Kuopid = 'Kuopid',
    Tampere = 'Tampere',
    Helsinki = 'Helsinki',
    Espoo = 'Espoo',
    Pori = 'Pori',
    Turku = 'Turku',
    Uppsala = 'Uppsala',
    Stockholm = 'Stockholm',
    Vasteras = 'Vasteras',
    Drebro = 'Drebro',
    Sundsvall = 'Sundsvall',
    Lulea = 'Lulea',
    Ostersund = 'Ostersund',
    Tallinn = 'Tallinn',
    Tartu = 'Tartu',
    Daugavpils = 'Daugavpils',
    Vilnius = 'Vilnius',
    Kaunas = 'Kaunas',
    Rica = 'Rica',
    Klaipeda = 'Klaipeda',
    Karlstad = 'Karlstad',
    Linkopinc = 'Linkopinc',
    Jonkoping = 'Jonkoping',
    Visby = 'Visby',
    Kristianstad = 'Kristianstad',
    Malmo = 'Malmo',
    Goteborg = 'Goteborg',
    Aalborg = 'Aalborg',
    Aarhus = 'Aarhus',
    Kobenhavn = 'Kobenhavn',
    Nykobingfalster = 'Nykobing Falster',
    Ringkobing = 'Ringkobing',
    Esbjerg = 'Esbjerg',
    Odense = 'Odense',
    Tromso = 'Tromso',
    Bood = 'Bood',
    Trondheim = 'Trondheim',
    Oslo = 'Oslo',
    Arendal = 'Arendal',
    Bergen = 'Bergen',
    Stavanger = 'Stavanger',
}

export const map: Map = {
    name: 'Northern Europe',
    cities: [
        { name: Cities.Oulu, region: Regions.Brown, x: 514, y: 376 },
        { name: Cities.Kuopid, region: Regions.Brown, x: 551, y: 474 },
        { name: Cities.Tampere, region: Regions.Brown, x: 484, y: 544 },
        { name: Cities.Helsinki, region: Regions.Brown, x: 513, y: 602 },
        { name: Cities.Espoo, region: Regions.Brown, x: 457, y: 603 },
        { name: Cities.Pori, region: Regions.Brown, x: 417, y: 540 },
        { name: Cities.Turku, region: Regions.Brown, x: 416, y: 579 },
        { name: Cities.Uppsala, region: Regions.Yellow, x: 365, y: 612 },
        { name: Cities.Stockholm, region: Regions.Yellow, x: 360, y: 642 },
        { name: Cities.Vasteras, region: Regions.Yellow, x: 308, y: 611 },
        { name: Cities.Drebro, region: Regions.Yellow, x: 304, y: 641 },
        { name: Cities.Sundsvall, region: Regions.Yellow, x: 332, y: 506 },
        { name: Cities.Lulea, region: Regions.Yellow, x: 423, y: 345 },
        { name: Cities.Ostersund, region: Regions.Yellow, x: 272, y: 462 },
        { name: Cities.Tallinn, region: Regions.Pink, x: 487, y: 642 },
        { name: Cities.Tartu, region: Regions.Pink, x: 544, y: 689 },
        { name: Cities.Daugavpils, region: Regions.Pink, x: 547, y: 771 },
        { name: Cities.Vilnius, region: Regions.Pink, x: 520, y: 819 },
        { name: Cities.Kaunas, region: Regions.Pink, x: 458, y: 811 },
        { name: Cities.Rica, region: Regions.Pink, x: 472, y: 734 },
        { name: Cities.Klaipeda, region: Regions.Pink, x: 411, y: 784 },
        { name: Cities.Karlstad, region: Regions.Purple, x: 246, y: 629 },
        { name: Cities.Linkopinc, region: Regions.Purple, x: 309, y: 676 },
        { name: Cities.Jonkoping, region: Regions.Purple, x: 285, y: 712 },
        { name: Cities.Visby, region: Regions.Purple, x: 364, y: 717 },
        { name: Cities.Kristianstad, region: Regions.Purple, x: 330, y: 750 },
        { name: Cities.Malmo, region: Regions.Purple, x: 268, y: 778 },
        { name: Cities.Goteborg, region: Regions.Purple, x: 231, y: 700 },
        { name: Cities.Aalborg, region: Regions.Orange, x: 188, y: 726 },
        { name: Cities.Aarhus, region: Regions.Orange, x: 191, y: 761 },
        { name: Cities.Kobenhavn, region: Regions.Orange, x: 216, y: 787 },
        { name: Cities.Nykobingfalster, region: Regions.Orange, x: 224, y: 815 },
        { name: Cities.Ringkobing, region: Regions.Orange, x: 133, y: 742 },
        { name: Cities.Esbjerg, region: Regions.Orange, x: 128, y: 769 },
        { name: Cities.Odense, region: Regions.Orange, x: 162, y: 797 },
        { name: Cities.Tromso, region: Regions.Red, x: 371, y: 122 },
        { name: Cities.Bood, region: Regions.Red, x: 276, y: 254 },
        { name: Cities.Trondheim, region: Regions.Red, x: 173, y: 450 },
        { name: Cities.Oslo, region: Regions.Red, x: 176, y: 606 },
        { name: Cities.Arendal, region: Regions.Red, x: 145, y: 651 },
        { name: Cities.Bergen, region: Regions.Red, x: 68, y: 586 },
        { name: Cities.Stavanger, region: Regions.Red, x: 72, y: 647 },
    ],
    connections: [
        { nodes: [Cities.Bood, Cities.Tromso], cost: 17 },
        { nodes: [Cities.Tromso, Cities.Oulu], cost: 25 },
        { nodes: [Cities.Oulu, Cities.Kuopid], cost: 10 },
        { nodes: [Cities.Lulea, Cities.Tromso], cost: 19 },
        { nodes: [Cities.Lulea, Cities.Oulu], cost: 13 },
        { nodes: [Cities.Oulu, Cities.Pori], cost: 15 },
        { nodes: [Cities.Oulu, Cities.Tampere], cost: 14 },
        { nodes: [Cities.Sundsvall, Cities.Lulea], cost: 16 },
        { nodes: [Cities.Lulea, Cities.Bood], cost: 16 },
        { nodes: [Cities.Bood, Cities.Ostersund], cost: 18 },
        { nodes: [Cities.Ostersund, Cities.Lulea], cost: 17 },
        { nodes: [Cities.Lulea, Cities.Pori], cost: 22 },
        { nodes: [Cities.Pori, Cities.Sundsvall], cost: 17 },
        { nodes: [Cities.Bood, Cities.Trondheim], cost: 21 },
        { nodes: [Cities.Trondheim, Cities.Bergen], cost: 17 },
        { nodes: [Cities.Trondheim, Cities.Oslo], cost: 17 },
        { nodes: [Cities.Oslo, Cities.Ostersund], cost: 18 },
        { nodes: [Cities.Ostersund, Cities.Karlstad], cost: 16 },
        { nodes: [Cities.Bergen, Cities.Oslo], cost: 15 },
        { nodes: [Cities.Oslo, Cities.Stavanger], cost: 11 },
        { nodes: [Cities.Stavanger, Cities.Arendal], cost: 8 },
        { nodes: [Cities.Arendal, Cities.Oslo], cost: 7 },
        { nodes: [Cities.Bergen, Cities.Stavanger], cost: 9 },
        { nodes: [Cities.Arendal, Cities.Ringkobing], cost: 19 },
        { nodes: [Cities.Ringkobing, Cities.Esbjerg], cost: 4 },
        { nodes: [Cities.Esbjerg, Cities.Odense], cost: 5 },
        { nodes: [Cities.Odense, Cities.Nykobingfalster], cost: 8 },
        { nodes: [Cities.Arendal, Cities.Aalborg], cost: 16 },
        { nodes: [Cities.Arendal, Cities.Goteborg], cost: 19 },
        { nodes: [Cities.Goteborg, Cities.Oslo], cost: 11 },
        { nodes: [Cities.Oslo, Cities.Karlstad], cost: 7 },
        { nodes: [Cities.Karlstad, Cities.Goteborg], cost: 9 },
        { nodes: [Cities.Karlstad, Cities.Jonkoping], cost: 9 },
        { nodes: [Cities.Karlstad, Cities.Linkopinc], cost: 7 },
        { nodes: [Cities.Tampere, Cities.Kuopid], cost: 10 },
        { nodes: [Cities.Tampere, Cities.Pori], cost: 4 },
        { nodes: [Cities.Tampere, Cities.Turku], cost: 5 },
        { nodes: [Cities.Tampere, Cities.Espoo], cost: 5 },
        { nodes: [Cities.Tampere, Cities.Helsinki], cost: 6 },
        { nodes: [Cities.Helsinki, Cities.Espoo], cost: 2 },
        { nodes: [Cities.Espoo, Cities.Tallinn], cost: 7 },
        { nodes: [Cities.Tallinn, Cities.Helsinki], cost: 7 },
        { nodes: [Cities.Visby, Cities.Kristianstad], cost: 13 },
        { nodes: [Cities.Visby, Cities.Klaipeda], cost: 19 },
        { nodes: [Cities.Visby, Cities.Rica], cost: 20 },
        { nodes: [Cities.Rica, Cities.Tallinn], cost: 11 },
        { nodes: [Cities.Tallinn, Cities.Tartu], cost: 5 },
        { nodes: [Cities.Tartu, Cities.Daugavpils], cost: 9 },
        { nodes: [Cities.Rica, Cities.Tartu], cost: 7 },
        { nodes: [Cities.Daugavpils, Cities.Kaunas], cost: 7 },
        { nodes: [Cities.Kaunas, Cities.Vilnius], cost: 3 },
        { nodes: [Cities.Kaunas, Cities.Klaipeda], cost: 7 },
        { nodes: [Cities.Klaipeda, Cities.Rica], cost: 8 },
        { nodes: [Cities.Rica, Cities.Kaunas], cost: 8 },
        { nodes: [Cities.Rica, Cities.Daugavpils], cost: 7 },
        { nodes: [Cities.Daugavpils, Cities.Vilnius], cost: 5 },
        { nodes: [Cities.Vasteras, Cities.Sundsvall], cost: 10 },
        { nodes: [Cities.Sundsvall, Cities.Ostersund], cost: 7 },
        { nodes: [Cities.Uppsala, Cities.Stockholm], cost: 2 },
        { nodes: [Cities.Uppsala, Cities.Turku], cost: 15 },
        { nodes: [Cities.Uppsala, Cities.Pori], cost: 17 },
        { nodes: [Cities.Uppsala, Cities.Sundsvall], cost: 11 },
        { nodes: [Cities.Vasteras, Cities.Drebro], cost: 5 },
        { nodes: [Cities.Drebro, Cities.Linkopinc], cost: 3 },
        { nodes: [Cities.Linkopinc, Cities.Stockholm], cost: 7 },
        { nodes: [Cities.Visby, Cities.Stockholm], cost: 12 },
        { nodes: [Cities.Visby, Cities.Linkopinc], cost: 9 },
        { nodes: [Cities.Jonkoping, Cities.Malmo], cost: 10 },
        { nodes: [Cities.Jonkoping, Cities.Kristianstad], cost: 8 },
        { nodes: [Cities.Kristianstad, Cities.Malmo], cost: 3 },
        { nodes: [Cities.Malmo, Cities.Kobenhavn], cost: 3 },
        { nodes: [Cities.Kobenhavn, Cities.Nykobingfalster], cost: 6 },
        { nodes: [Cities.Odense, Cities.Aarhus], cost: 7 },
        { nodes: [Cities.Aarhus, Cities.Aalborg], cost: 3 },
        { nodes: [Cities.Aalborg, Cities.Goteborg], cost: 11 },
        { nodes: [Cities.Kobenhavn, Cities.Goteborg], cost: 18 },
        { nodes: [Cities.Goteborg, Cities.Jonkoping], cost: 4 },
        { nodes: [Cities.Trondheim, Cities.Ostersund], cost: 9 },
        { nodes: [Cities.Vasteras, Cities.Stockholm], cost: 4 },
        { nodes: [Cities.Esbjerg, Cities.Aarhus], cost: 5 },
        { nodes: [Cities.Jonkoping, Cities.Linkopinc], cost: 5 },
        { nodes: [Cities.Kobenhavn, Cities.Jonkoping], cost: 12 },
        { nodes: [Cities.Karlstad, Cities.Drebro], cost: 4 },
        { nodes: [Cities.Vasteras, Cities.Uppsala], cost: 2 },
        { nodes: [Cities.Odense, Cities.Kobenhavn], cost: 7 },
        { nodes: [Cities.Kobenhavn, Cities.Aarhus], cost: 10 },
        { nodes: [Cities.Ringkobing, Cities.Aalborg], cost: 5 },
        { nodes: [Cities.Linkopinc, Cities.Kristianstad], cost: 9 },
        { nodes: [Cities.Drebro, Cities.Stockholm], cost: 7 },
        { nodes: [Cities.Espoo, Cities.Turku], cost: 4 },
        { nodes: [Cities.Pori, Cities.Turku], cost: 4 },
    ],
};
