import { Map } from './gamestate';

export enum Regions {
    Purple = 'purple',
    Green = 'green',
    Red = 'red',
    Yellow = 'yellow',
    Cyan = 'cyan',
    Brown = 'brown',
}

export enum Cities {
    Seattle = 'Seattle',
    Portland = 'Portland',
    Boise = 'Boise',
    Billings = 'Billings',
    Cheyenne = 'Cheyenne',
    Denver = 'Denver',
    Omaha = 'Omaha',
    SanFrancisco = 'San Francisco',
    LosAngeles = 'Los Angeles',
    SanDiego = 'San Diego',
    LasVegas = 'Las Vegas',
    SaltlakeCity = 'Saltlake City',
    Phoenix = 'Phoenix',
    SantaFe = 'Santa Fe',
    KansasCity = 'Kansas City',
    OklahomaCity = 'Oklahoma City',
    Dallas = 'Dallas',
    Houston = 'Houston',
    Menphis = 'Menphis',
    Birmingham = 'Birmingham',
    NewOrleans = 'New Orleans',
    Fargo = 'Fargo',
    Duluth = 'Duluth',
    Minneapolis = 'Minneapolis',
    Chicago = 'Chicago',
    StLouis = 'St. Louis',
    Cincinnati = 'Cincinnati',
    Knoxvile = 'Knoxvile',
    Detroit = 'Detroit',
    Buffalo = 'Buffalo',
    Pittsburgh = 'Pittsburgh',
    Boston = 'Boston',
    NewYork = 'New York',
    Philadelphia = 'Philadelphia',
    Washington = 'Washington',
    Horecin = 'Horecin',
    Raleigh = 'Raleigh',
    Atlanta = 'Atlanta',
    Savannah = 'Savannah',
    Jacksonvile = 'Jacksonvile',
    Tampa = 'Tampa',
    Miami = 'Miami',
    Flensburg = 'Flensburg',
    Kiel = 'Kiel',
    Hamburg = 'Hamburg',
    Hannover = 'Hannover',
    Bremen = 'Bremen',
    Wilhelmshaven = 'Wilhelmshaven',
    Cuxhaven = 'Cuxhaven',
    Lubeck = 'Lubeck',
    Rostock = 'Rostock',
    Schwerin = 'Schwerin',
    Torgelow = 'Torgelow',
    Magdeburg = 'Magdeburg',
    Berlin = 'Berlin',
    FrankfurtO = 'Frankfurt-O',
    Halle = 'Halle',
    Leipzig = 'Leipzig',
    Dresden = 'Dresden',
    Erfurt = 'Erfurt',
    Fulda = 'Fulda',
    Würzburg = 'Würzburg',
    Nurnberg = 'Nurnberg',
    Osnabrück = 'Osnabrück',
    Münster = 'Münster',
    Essen = 'Essen',
    Duisburg = 'Duisburg',
    Dortmund = 'Dortmund',
    Dusseldorf = 'Dusseldorf',
    Kassel = 'Kassel',
    Aachen = 'Aachen',
    Köln = 'Köln',
    Trier = 'Trier',
    Wiesbaden = 'Wiesbaden',
    FrankfurtM = 'Frankfurt-M',
    Saarbrücken = 'Saarbrücken',
    Mannheim = 'Mannheim',
    Freiburg = 'Freiburg',
    Stuttgart = 'Stuttgart',
    Konstanz = 'Konstanz',
    Augsburg = 'Augsburg',
    Regensburg = 'Regensburg',
    München = 'München',
    Passau = 'Passau',
}

const maps: Map[] = [
    {
        name: 'USA',
        cities: [
            { name: Cities.Seattle, region: Regions.Purple, x: 74, y: 99 },
            { name: Cities.Portland, region: Regions.Purple, x: 45, y: 167 },
            { name: Cities.Boise, region: Regions.Purple, x: 180, y: 220 },
            { name: Cities.Billings, region: Regions.Purple, x: 345, y: 180 },
            { name: Cities.Cheyenne, region: Regions.Purple, x: 410, y: 280 },
            { name: Cities.Denver, region: Regions.Purple, x: 400, y: 333 },
            { name: Cities.Omaha, region: Regions.Purple, x: 566, y: 293 },
            { name: Cities.SanFrancisco, region: Regions.Cyan, x: 48, y: 371 },
            { name: Cities.LosAngeles, region: Regions.Cyan, x: 116, y: 460 },
            { name: Cities.SanDiego, region: Regions.Cyan, x: 157, y: 507 },
            { name: Cities.LasVegas, region: Regions.Cyan, x: 200, y: 410 },
            { name: Cities.SaltlakeCity, region: Regions.Cyan, x: 266, y: 311 },
            { name: Cities.Phoenix, region: Regions.Cyan, x: 260, y: 486 },
            { name: Cities.SantaFe, region: Regions.Cyan, x: 371, y: 435 },
            { name: Cities.KansasCity, region: Regions.Red, x: 587, y: 356 },
            { name: Cities.OklahomaCity, region: Regions.Red, x: 550, y: 437 },
            { name: Cities.Dallas, region: Regions.Red, x: 560, y: 504 },
            { name: Cities.Houston, region: Regions.Red, x: 569, y: 571 },
            { name: Cities.Menphis, region: Regions.Red, x: 678, y: 449 },
            { name: Cities.Birmingham, region: Regions.Red, x: 739, y: 486 },
            { name: Cities.NewOrleans, region: Regions.Red, x: 674, y: 570 },
            { name: Cities.Fargo, region: Regions.Yellow, x: 551, y: 152 },
            { name: Cities.Duluth, region: Regions.Yellow, x: 637, y: 133 },
            { name: Cities.Minneapolis, region: Regions.Yellow, x: 621, y: 190 },
            { name: Cities.Chicago, region: Regions.Yellow, x: 716, y: 281 },
            { name: Cities.StLouis, region: Regions.Yellow, x: 678, y: 362 },
            { name: Cities.Cincinnati, region: Regions.Yellow, x: 795, y: 348 },
            { name: Cities.Knoxvile, region: Regions.Yellow, x: 796, y: 422 },
            { name: Cities.Detroit, region: Regions.Brown, x: 803, y: 262 },
            { name: Cities.Buffalo, region: Regions.Brown, x: 913, y: 251 },
            { name: Cities.Pittsburgh, region: Regions.Brown, x: 884, y: 316 },
            { name: Cities.Boston, region: Regions.Brown, x: 1052, y: 252 },
            { name: Cities.NewYork, region: Regions.Brown, x: 1010, y: 290 },
            { name: Cities.Philadelphia, region: Regions.Brown, x: 985, y: 330 },
            { name: Cities.Washington, region: Regions.Brown, x: 934, y: 357 },
            { name: Cities.Horecin, region: Regions.Green, x: 969, y: 405 },
            { name: Cities.Raleigh, region: Regions.Green, x: 915, y: 437 },
            { name: Cities.Atlanta, region: Regions.Green, x: 801, y: 487 },
            { name: Cities.Savannah, region: Regions.Green, x: 867, y: 507 },
            { name: Cities.Jacksonvile, region: Regions.Green, x: 861, y: 559 },
            { name: Cities.Tampa, region: Regions.Green, x: 819, y: 621 },
            { name: Cities.Miami, region: Regions.Green, x: 883, y: 670 },
        ],
        connections: [
            { nodes: [Cities.Seattle, Cities.Portland], cost: 3 },
            { nodes: [Cities.Seattle, Cities.Boise], cost: 12 },
            { nodes: [Cities.Seattle, Cities.Billings], cost: 9 },
            { nodes: [Cities.Portland, Cities.Boise], cost: 13 },
            { nodes: [Cities.Portland, Cities.SanFrancisco], cost: 24 },
            { nodes: [Cities.Boise, Cities.Billings], cost: 12 },
            { nodes: [Cities.Boise, Cities.Cheyenne], cost: 24 },
            { nodes: [Cities.Boise, Cities.SanFrancisco], cost: 23 },
            { nodes: [Cities.Boise, Cities.SaltlakeCity], cost: 8 },
            { nodes: [Cities.Billings, Cities.Cheyenne], cost: 9 },
            { nodes: [Cities.Billings, Cities.Fargo], cost: 17 },
            { nodes: [Cities.Billings, Cities.Minneapolis], cost: 18 },
            { nodes: [Cities.Cheyenne, Cities.Denver], cost: 0 },
            { nodes: [Cities.Cheyenne, Cities.Omaha], cost: 14 },
            { nodes: [Cities.Cheyenne, Cities.Minneapolis], cost: 18 },
            { nodes: [Cities.Denver, Cities.SaltlakeCity], cost: 21 },
            { nodes: [Cities.Denver, Cities.SantaFe], cost: 13 },
            { nodes: [Cities.Denver, Cities.KansasCity], cost: 16 },
            { nodes: [Cities.Omaha, Cities.KansasCity], cost: 5 },
            { nodes: [Cities.Omaha, Cities.Minneapolis], cost: 8 },
            { nodes: [Cities.Omaha, Cities.Chicago], cost: 13 },
            { nodes: [Cities.SanFrancisco, Cities.LosAngeles], cost: 9 },
            { nodes: [Cities.SanFrancisco, Cities.LasVegas], cost: 14 },
            { nodes: [Cities.SanFrancisco, Cities.SaltlakeCity], cost: 27 },
            { nodes: [Cities.LosAngeles, Cities.SanDiego], cost: 3 },
            { nodes: [Cities.LosAngeles, Cities.LasVegas], cost: 9 },
            { nodes: [Cities.SanDiego, Cities.LasVegas], cost: 9 },
            { nodes: [Cities.SanDiego, Cities.Phoenix], cost: 14 },
            { nodes: [Cities.LasVegas, Cities.SaltlakeCity], cost: 18 },
            { nodes: [Cities.LasVegas, Cities.Phoenix], cost: 15 },
            { nodes: [Cities.LasVegas, Cities.SantaFe], cost: 27 },
            { nodes: [Cities.SaltlakeCity, Cities.SantaFe], cost: 28 },
            { nodes: [Cities.Phoenix, Cities.SantaFe], cost: 18 },
            { nodes: [Cities.SantaFe, Cities.KansasCity], cost: 16 },
            { nodes: [Cities.SantaFe, Cities.OklahomaCity], cost: 15 },
            { nodes: [Cities.SantaFe, Cities.Dallas], cost: 16 },
            { nodes: [Cities.SantaFe, Cities.Houston], cost: 21 },
            { nodes: [Cities.KansasCity, Cities.OklahomaCity], cost: 8 },
            { nodes: [Cities.KansasCity, Cities.Menphis], cost: 12 },
            { nodes: [Cities.KansasCity, Cities.Chicago], cost: 8 },
            { nodes: [Cities.KansasCity, Cities.StLouis], cost: 6 },
            { nodes: [Cities.OklahomaCity, Cities.Dallas], cost: 3 },
            { nodes: [Cities.OklahomaCity, Cities.Menphis], cost: 14 },
            { nodes: [Cities.Dallas, Cities.Houston], cost: 5 },
            { nodes: [Cities.Dallas, Cities.Menphis], cost: 12 },
            { nodes: [Cities.Dallas, Cities.NewOrleans], cost: 12 },
            { nodes: [Cities.Houston, Cities.NewOrleans], cost: 8 },
            { nodes: [Cities.Menphis, Cities.Birmingham], cost: 6 },
            { nodes: [Cities.Menphis, Cities.NewOrleans], cost: 7 },
            { nodes: [Cities.Menphis, Cities.StLouis], cost: 7 },
            { nodes: [Cities.Birmingham, Cities.NewOrleans], cost: 11 },
            { nodes: [Cities.Birmingham, Cities.Atlanta], cost: 3 },
            { nodes: [Cities.Birmingham, Cities.Jacksonvile], cost: 9 },
            { nodes: [Cities.NewOrleans, Cities.Jacksonvile], cost: 16 },
            { nodes: [Cities.Fargo, Cities.Duluth], cost: 6 },
            { nodes: [Cities.Fargo, Cities.Minneapolis], cost: 6 },
            { nodes: [Cities.Duluth, Cities.Minneapolis], cost: 5 },
            { nodes: [Cities.Duluth, Cities.Chicago], cost: 12 },
            { nodes: [Cities.Duluth, Cities.Detroit], cost: 15 },
            { nodes: [Cities.Minneapolis, Cities.Chicago], cost: 8 },
            { nodes: [Cities.Chicago, Cities.StLouis], cost: 10 },
            { nodes: [Cities.Chicago, Cities.Cincinnati], cost: 7 },
            { nodes: [Cities.Chicago, Cities.Detroit], cost: 7 },
            { nodes: [Cities.StLouis, Cities.Cincinnati], cost: 12 },
            { nodes: [Cities.StLouis, Cities.Atlanta], cost: 12 },
            { nodes: [Cities.Cincinnati, Cities.Knoxvile], cost: 6 },
            { nodes: [Cities.Cincinnati, Cities.Detroit], cost: 4 },
            { nodes: [Cities.Cincinnati, Cities.Pittsburgh], cost: 7 },
            { nodes: [Cities.Cincinnati, Cities.Raleigh], cost: 15 },
            { nodes: [Cities.Knoxvile, Cities.Atlanta], cost: 5 },
            { nodes: [Cities.Detroit, Cities.Buffalo], cost: 7 },
            { nodes: [Cities.Detroit, Cities.Pittsburgh], cost: 6 },
            { nodes: [Cities.Buffalo, Cities.Pittsburgh], cost: 7 },
            { nodes: [Cities.Buffalo, Cities.NewYork], cost: 8 },
            { nodes: [Cities.Pittsburgh, Cities.Washington], cost: 6 },
            { nodes: [Cities.Pittsburgh, Cities.Raleigh], cost: 7 },
            { nodes: [Cities.Boston, Cities.NewYork], cost: 3 },
            { nodes: [Cities.NewYork, Cities.Philadelphia], cost: 0 },
            { nodes: [Cities.Philadelphia, Cities.Washington], cost: 3 },
            { nodes: [Cities.Washington, Cities.Horecin], cost: 5 },
            { nodes: [Cities.Horecin, Cities.Raleigh], cost: 3 },
            { nodes: [Cities.Raleigh, Cities.Atlanta], cost: 7 },
            { nodes: [Cities.Raleigh, Cities.Savannah], cost: 7 },
            { nodes: [Cities.Atlanta, Cities.Savannah], cost: 7 },
            { nodes: [Cities.Savannah, Cities.Jacksonvile], cost: 0 },
            { nodes: [Cities.Jacksonvile, Cities.Tampa], cost: 4 },
            { nodes: [Cities.Tampa, Cities.Miami], cost: 4 },
        ],
    },
    {
        name: 'Germany',
        cities: [
            { name: Cities.Flensburg, region: Regions.Green, x: 37, y: 427 },
            { name: Cities.Kiel, region: Regions.Green, x: 106, y: 392 },
            { name: Cities.Hamburg, region: Regions.Green, x: 212, y: 396 },
            { name: Cities.Hannover, region: Regions.Green, x: 378, y: 395 },
            { name: Cities.Bremen, region: Regions.Green, x: 276, y: 463 },
            { name: Cities.Wilhelmshaven, region: Regions.Green, x: 211, y: 521 },
            { name: Cities.Cuxhaven, region: Regions.Green, x: 168, y: 474 },
            { name: Cities.Lubeck, region: Regions.Brown, x: 153, y: 341 },
            { name: Cities.Rostock, region: Regions.Brown, x: 128, y: 256 },
            { name: Cities.Schwerin, region: Regions.Brown, x: 217, y: 297 },
            { name: Cities.Torgelow, region: Regions.Brown, x: 210, y: 126 },
            { name: Cities.Magdeburg, region: Regions.Brown, x: 389, y: 271 },
            { name: Cities.Berlin, region: Regions.Brown, x: 355, y: 170 },
            { name: Cities.FrankfurtO, region: Regions.Brown, x: 381, y: 99 },
            { name: Cities.Halle, region: Regions.Yellow, x: 493, y: 259 },
            { name: Cities.Leipzig, region: Regions.Yellow, x: 526, y: 222 },
            { name: Cities.Dresden, region: Regions.Yellow, x: 572, y: 126 },
            { name: Cities.Erfurt, region: Regions.Yellow, x: 567, y: 309 },
            { name: Cities.Fulda, region: Regions.Yellow, x: 628, y: 398 },
            { name: Cities.Würzburg, region: Regions.Yellow, x: 735, y: 386 },
            { name: Cities.Nurnberg, region: Regions.Yellow, x: 780, y: 309 },
            { name: Cities.Osnabrück, region: Regions.Red, x: 359, y: 516 },
            { name: Cities.Münster, region: Regions.Red, x: 427, y: 554 },
            { name: Cities.Essen, region: Regions.Red, x: 475, y: 603 },
            { name: Cities.Duisburg, region: Regions.Red, x: 456, y: 645 },
            { name: Cities.Dortmund, region: Regions.Red, x: 505, y: 543 },
            { name: Cities.Dusseldorf, region: Regions.Red, x: 537, y: 635 },
            { name: Cities.Kassel, region: Regions.Red, x: 524, y: 430 },
            { name: Cities.Aachen, region: Regions.Cyan, x: 614, y: 654 },
            { name: Cities.Köln, region: Regions.Cyan, x: 590, y: 589 },
            { name: Cities.Trier, region: Regions.Cyan, x: 739, y: 628 },
            { name: Cities.Wiesbaden, region: Regions.Cyan, x: 697, y: 514 },
            { name: Cities.FrankfurtM, region: Regions.Cyan, x: 672, y: 473 },
            { name: Cities.Saarbrücken, region: Regions.Cyan, x: 818, y: 568 },
            { name: Cities.Mannheim, region: Regions.Cyan, x: 796, y: 479 },
            { name: Cities.Freiburg, region: Regions.Purple, x: 966, y: 537 },
            { name: Cities.Stuttgart, region: Regions.Purple, x: 884, y: 458 },
            { name: Cities.Konstanz, region: Regions.Purple, x: 1011, y: 459 },
            { name: Cities.Augsburg, region: Regions.Purple, x: 911, y: 346 },
            { name: Cities.Regensburg, region: Regions.Purple, x: 846, y: 256 },
            { name: Cities.München, region: Regions.Purple, x: 967, y: 278 },
            { name: Cities.Passau, region: Regions.Purple, x: 904, y: 153 },
        ],
        connections: [
            { nodes: [Cities.Flensburg, Cities.Kiel], cost: 4 },
            { nodes: [Cities.Kiel, Cities.Hamburg], cost: 8 },
            { nodes: [Cities.Kiel, Cities.Lubeck], cost: 4 },
            { nodes: [Cities.Hamburg, Cities.Hannover], cost: 17 },
            { nodes: [Cities.Hamburg, Cities.Bremen], cost: 11 },
            { nodes: [Cities.Hamburg, Cities.Cuxhaven], cost: 11 },
            { nodes: [Cities.Hamburg, Cities.Lubeck], cost: 6 },
            { nodes: [Cities.Hamburg, Cities.Schwerin], cost: 8 },
            { nodes: [Cities.Bremen, Cities.Wilhelmshaven], cost: 11 },
            { nodes: [Cities.Bremen, Cities.Hannover], cost: 10 },
            { nodes: [Cities.Bremen, Cities.Cuxhaven], cost: 8 },
            { nodes: [Cities.Bremen, Cities.Osnabrück], cost: 11 },
            { nodes: [Cities.Hannover, Cities.Schwerin], cost: 19 },
            { nodes: [Cities.Hannover, Cities.Magdeburg], cost: 15 },
            { nodes: [Cities.Hannover, Cities.Erfurt], cost: 19 },
            { nodes: [Cities.Hannover, Cities.Osnabrück], cost: 16 },
            { nodes: [Cities.Hannover, Cities.Kassel], cost: 15 },
            { nodes: [Cities.Wilhelmshaven, Cities.Osnabrück], cost: 14 },
            { nodes: [Cities.Lubeck, Cities.Schwerin], cost: 6 },
            { nodes: [Cities.Schwerin, Cities.Rostock], cost: 6 },
            { nodes: [Cities.Schwerin, Cities.Torgelow], cost: 19 },
            { nodes: [Cities.Schwerin, Cities.Berlin], cost: 18 },
            { nodes: [Cities.Schwerin, Cities.Magdeburg], cost: 16 },
            { nodes: [Cities.Torgelow, Cities.Rostock], cost: 19 },
            { nodes: [Cities.Torgelow, Cities.Berlin], cost: 15 },
            { nodes: [Cities.Berlin, Cities.Magdeburg], cost: 10 },
            { nodes: [Cities.Berlin, Cities.FrankfurtO], cost: 6 },
            { nodes: [Cities.Berlin, Cities.Halle], cost: 17 },
            { nodes: [Cities.Magdeburg, Cities.Halle], cost: 11 },
            { nodes: [Cities.FrankfurtO, Cities.Leipzig], cost: 21 },
            { nodes: [Cities.FrankfurtO, Cities.Dresden], cost: 16 },
            { nodes: [Cities.Halle, Cities.Leipzig], cost: 0 },
            { nodes: [Cities.Leipzig, Cities.Dresden], cost: 13 },
            { nodes: [Cities.Erfurt, Cities.Halle], cost: 6 },
            { nodes: [Cities.Erfurt, Cities.Dresden], cost: 19 },
            { nodes: [Cities.Erfurt, Cities.Nurnberg], cost: 21 },
            { nodes: [Cities.Erfurt, Cities.Fulda], cost: 13 },
            { nodes: [Cities.Erfurt, Cities.Kassel], cost: 15 },
            { nodes: [Cities.Fulda, Cities.Würzburg], cost: 11 },
            { nodes: [Cities.Fulda, Cities.Kassel], cost: 8 },
            { nodes: [Cities.Fulda, Cities.FrankfurtM], cost: 8 },
            { nodes: [Cities.Würzburg, Cities.Nurnberg], cost: 8 },
            { nodes: [Cities.Würzburg, Cities.FrankfurtM], cost: 13 },
            { nodes: [Cities.Würzburg, Cities.Mannheim], cost: 10 },
            { nodes: [Cities.Würzburg, Cities.Stuttgart], cost: 12 },
            { nodes: [Cities.Würzburg, Cities.Augsburg], cost: 19 },
            { nodes: [Cities.Nurnberg, Cities.Augsburg], cost: 18 },
            { nodes: [Cities.Nurnberg, Cities.Regensburg], cost: 12 },
            { nodes: [Cities.Osnabrück, Cities.Münster], cost: 7 },
            { nodes: [Cities.Osnabrück, Cities.Kassel], cost: 20 },
            { nodes: [Cities.Münster, Cities.Essen], cost: 6 },
            { nodes: [Cities.Münster, Cities.Dortmund], cost: 2 },
            { nodes: [Cities.Essen, Cities.Duisburg], cost: 0 },
            { nodes: [Cities.Essen, Cities.Dusseldorf], cost: 2 },
            { nodes: [Cities.Essen, Cities.Dortmund], cost: 4 },
            { nodes: [Cities.Dortmund, Cities.Kassel], cost: 18 },
            { nodes: [Cities.Dortmund, Cities.Köln], cost: 10 },
            { nodes: [Cities.Dortmund, Cities.FrankfurtM], cost: 20 },
            { nodes: [Cities.Kassel, Cities.FrankfurtM], cost: 13 },
            { nodes: [Cities.Dusseldorf, Cities.Aachen], cost: 9 },
            { nodes: [Cities.Dusseldorf, Cities.Köln], cost: 4 },
            { nodes: [Cities.Aachen, Cities.Köln], cost: 7 },
            { nodes: [Cities.Aachen, Cities.Trier], cost: 19 },
            { nodes: [Cities.Trier, Cities.Köln], cost: 20 },
            { nodes: [Cities.Trier, Cities.Wiesbaden], cost: 18 },
            { nodes: [Cities.Trier, Cities.Saarbrücken], cost: 11 },
            { nodes: [Cities.Wiesbaden, Cities.FrankfurtM], cost: 0 },
            { nodes: [Cities.Wiesbaden, Cities.Köln], cost: 21 },
            { nodes: [Cities.Wiesbaden, Cities.Saarbrücken], cost: 10 },
            { nodes: [Cities.Wiesbaden, Cities.Mannheim], cost: 11 },
            { nodes: [Cities.Mannheim, Cities.Saarbrücken], cost: 11 },
            { nodes: [Cities.Mannheim, Cities.Stuttgart], cost: 6 },
            { nodes: [Cities.Stuttgart, Cities.Saarbrücken], cost: 17 },
            { nodes: [Cities.Stuttgart, Cities.Freiburg], cost: 16 },
            { nodes: [Cities.Stuttgart, Cities.Konstanz], cost: 16 },
            { nodes: [Cities.Stuttgart, Cities.Augsburg], cost: 15 },
            { nodes: [Cities.Konstanz, Cities.Freiburg], cost: 14 },
            { nodes: [Cities.Konstanz, Cities.Augsburg], cost: 17 },
            { nodes: [Cities.Regensburg, Cities.Augsburg], cost: 13 },
            { nodes: [Cities.Regensburg, Cities.München], cost: 10 },
            { nodes: [Cities.Regensburg, Cities.Passau], cost: 12 },
            { nodes: [Cities.Augsburg, Cities.München], cost: 6 },
            { nodes: [Cities.Passau, Cities.München], cost: 14 },
        ],
    },
];

export default maps;
