name: Viewer - Test
on:
    push:
        paths:
            - '.github/workflows/viewer-test.yml'
            - 'viewer/**'
        branches:
            - master
    pull_request:
        paths:
            - '.github/workflows/viewer-test.yml'
            - 'viewer/**'

defaults:
    run:
        working-directory: viewer

jobs:
    test_and_build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: corepack enable
            - run: pnpm install
            # - run: pnpm lint
            # - run: pnpm test
            - run: pnpm build
